apiVersion: v1
kind: Service
metadata:
  name: mobilenet-api-service
spec:
  type: NodePort
  selector:
    app: mobilenet-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30081
